version: "3.3"
services:
  servidor:
    container_name: TqTravel
    restart: always
    build: ./backend
    ports:
      - "2000:3000"
    volumes:
      - ./backend/src:/usr/src/app/src:rw
      - ./backend/tokens:/usr/src/app/tokens
      - ./backend/credentials.json:/usr/src/app/credentials.json
    environment:
      - PORT=3000
      - BD_HOST=144.126.212.222
      - BD_USER=root
      - BD_PASSWORD=C0l0mb1@
      - DATABASE=tqtravel
      - BD_PORT=3306
